/*******************************************************************************
 * Copyright (c) 2012, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @header          ...
 * @author          Jean-David Gadina <macmade@eosgarden>
 * @copyright       (c) 2012, eosgarden
 * @abstract        ...
 */

#import <Foundation/Foundation.h>

@class AsyncSocket;
@class EOSFTPServer;
@class EOSFTPServerDataConnection;

@interface EOSFTPServerConnection: NSObject
{
@protected
    
    AsyncSocket                * _connectionSocket;
    EOSFTPServer               * _server;
    EOSFTPServerTransferMode     _transferMode;
    NSUInteger                   _dataPort;
    EOSFTPServerDataConnection * _dataConnection;
    NSMutableArray             * _queuedData;
    NSString                   * _username;
    BOOL                         _authenticated;
    
@private
    
    id _EOSFTPServerConnection_Reserved[ 5 ] __attribute__( ( unused ) );
}

@property( atomic, readwrite, assign ) NSString * username;
@property( atomic, readwrite, assign ) BOOL       authenticated;

- ( id )initWithSocket: ( AsyncSocket * )socket server: ( EOSFTPServer * )server;
- ( void )sendMessage: ( NSString * )message;

@end
