/*******************************************************************************
 * Copyright (c) 2012, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @file            ...
 * @author          Jean-David Gadina <macmade@eosgarden>
 * @copyright       (c) 2012, eosgarden
 * @abstract        ...
 */

#import "EOSFTPServer+Private.h"
#import "EOSFTPServerConnection.h"

@implementation EOSFTPServer( Private )

- ( void )unrecognizedCommand: ( NSString * )command connection: ( EOSFTPServerConnection * )connection
{
    ( void )command;
    
    [ connection sendMessage: [ self formattedMessage: [ self messageForReplyCode: 502 ] code: 502 ] ];
}

- ( NSString * )formattedMessage: ( NSString * )message code: ( EOSFTPServerReplyCode )code
{
    NSMutableArray * lines;
    NSString       * firstLine;
    NSString       * lastLine;
    NSString       * formattedMessage;
    
    lines = [ [ message componentsSeparatedByString: @"\n" ] mutableCopy ];
    
    if( lines.count > 1 )
    {
        firstLine = [ [ [ lines objectAtIndex: 0 ] retain ] autorelease ];
        lastLine  = [ [ [ lines lastObject ] retain ] autorelease ];
        
        [ lines removeObjectAtIndex: lines.count - 1 ];
        [ lines removeObjectAtIndex: 0 ];
        
        if( lines.count > 0 )
        {
            formattedMessage = [ NSString stringWithFormat: @"%u-%@\n%@\n214 %@", code, firstLine, [ lines componentsJoinedByString: @"\n" ], lastLine ];
        }
        else
        {
            formattedMessage = [ NSString stringWithFormat: @"%u-%@\n214 %@", code, firstLine, lastLine ];
        }
    }
    else
    {
        formattedMessage = [ NSString stringWithFormat: @"%u %@", code, message ];
    }
    
    [ lines release ];
    
    return formattedMessage;
}

@end
