/*******************************************************************************
 * Copyright (c) 2012, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @file            ...
 * @author          Jean-David Gadina - www.xs-labs.com
 * @copyright       (c) 2012, XS-Labs
 * @abstract        ...
 */

#import "EOSFTPServerDataConnection+AsyncSocketDelegate.h"

@implementation EOSFTPServerDataConnection( AsyncSocketDelegate )

- ( BOOL )onSocketWillConnect: ( AsyncSocket * )socket
{
    ( void )socket;
    
    EOS_FTP_DEBUG( @"Socket will connect on port %u", [ socket localPort ] );
    
    [ _dataSocket readDataWithTimeout: EOS_FTP_SERVER_READ_TIMEOUT tag: 0 ];
    
    return YES;
}

- ( void )onSocket: ( AsyncSocket * )socket didAcceptNewSocket: ( AsyncSocket * )newSocket
{
    ( void )socket;
    ( void )newSocket;
    
    EOS_FTP_DEBUG( @"New socket accepted on port %u", [ newSocket localPort ] );
}

- ( void )onSocket: ( AsyncSocket * )socket didReadData: ( NSData * )data withTag: ( long )tag
{
    ( void )socket;
    ( void )tag;
    
    EOS_FTP_DEBUG( @"Data read (tag: %li)", tag );
    
    [ _dataSocket readDataWithTimeout: EOS_FTP_SERVER_READ_TIMEOUT tag: EOS_FTP_SERVER_CLIENT_REQUEST ];	
    [ _receivedData release ];
    
    _receivedData = ( NSMutableData * )[ data retain ];
    
    if( [ _delegate respondsToSelector: @selector( dataConnectionDidReadData: ) ] )
    {
        [ _delegate performSelector: @selector( dataConnectionDidReadData: ) withObject: self ];
    }
    
    [ _receivedData release ];
    
    _connectionState = EOSFTPServerConnectionStateClientSent;
}

- ( void )onSocket: ( AsyncSocket * )socket didWriteDataWithTag: ( long )tag
{
    ( void )socket;
    ( void )tag;
    
    EOS_FTP_DEBUG( @"Data written (tag: %li)", tag );
    
    if( [ _delegate respondsToSelector: @selector( dataConnectionDidWriteData: ) ] )
    {
        [ _delegate performSelector: @selector( dataConnectionDidWriteData: ) withObject: self ];
    }
    
    [ _dataSocket readDataWithTimeout: EOS_FTP_SERVER_READ_TIMEOUT tag: EOS_FTP_SERVER_CLIENT_REQUEST ];
}

- ( void )onSocket: ( AsyncSocket * )socket willDisconnectWithError: ( NSError * )error
{
    ( void )socket;
    ( void )error;
    
    EOS_FTP_DEBUG( @"Socket will disconnect with error: %@", error );
    
    if( [ _delegate respondsToSelector: @selector( dataConnectionDidFinishReading: ) ] )
    {
        [ _delegate performSelector: @selector( dataConnectionDidFinishReading: ) withObject: self ];
    }
}

- ( BOOL )onReadStreamEnded: ( AsyncSocket * )socket
{
    ( void )socket;
    
    if( _connectionState == EOSFTPServerConnectionStateClientSent || _connectionState == EOSFTPServerConnectionStateClientSending )
    {
        return YES;
    }
    
    return NO;
}

@end
