/*******************************************************************************
 * Copyright (c) 2012, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @file            ...
 * @author          Jean-David Gadina <macmade@eosgarden>
 * @copyright       (c) 2012, eosgarden
 * @abstract        ...
 */

#import "EOSFTPServerDesktopMainWindowController.h"
#import "EOSFTPServerDesktopMainWindowController+NSTableViewDataSource.h"
#import "EOSFTPServerDesktopMainWindowController+NSTableViewDelegate.h"
#import "EOSFTPServer.h"

@implementation EOSFTPServerDesktopMainWindowController

@synthesize tableView       = _tableView;
@synthesize startButton     = _startButton;
@synthesize stopButton      = _stopButton;
@synthesize allowAnonymous  = _allowAnonymous;
@synthesize serverPort      = _serverPort;

- ( id )init
{
    if( ( self = [ self initWithWindowNibName: @"MainWindow" owner: self ] ) )
    {
        _server = [ [ EOSFTPServer alloc ] initWithPort: 2121 ];
    }
    
    return self;
}

- ( void )dealloc
{
    [ _tableView        release ];
    [ _startButton      release ];
    [ _stopButton       release ];
    [ _allowAnonymous   release ];
    [ _serverPort       release ];
    [ _server           release ];
    [ _users            release ];
    
    [ super dealloc ];
}

- ( void )windowDidLoad
{
    [ super windowDidLoad ];
    
    _users = [ [ [ NSUserDefaults standardUserDefaults ] objectForKey: @"Users" ] mutableCopy ];
    
    [ _serverPort     setStringValue:  [ NSString stringWithFormat: NSLocalizedString( @"ServerPort", nil ), _server.port ] ];
    [ _allowAnonymous setIntegerValue: [ [ [ NSUserDefaults standardUserDefaults ] objectForKey: @"AllowAnonymous" ] integerValue ] ];
    
    _tableView.dataSource = self;
    _tableView.delegate   = self;
}

- ( IBAction )addUser: ( id )sender
{
    ( void )sender;
}

- ( IBAction )deleteUser: ( id )sender
{
    ( void )sender;
}

- ( IBAction )start: ( id )sender
{
    ( void )sender;
}

- ( IBAction )stop: ( id )sender
{
    ( void )sender;
}

- ( IBAction )allowAnonymous: ( id )sender
{
    ( void )sender;
}

@end
